### ISSUE TITLE
Requirements not properly installed

### ISSUE THREAD

**Issue by cristi-zz** [timeseriesAI/timeseriesAI#10]
Hi! I am trying to use your library.

I tried first installing from git and when launching a jupyter with ``from tsai.all import *`` I got some missing packages.

I installed from pip, same thing. Here they are (they are NOT exclusive, because I already have fastai and other libraries so some requirements were already installed)

    pywavelet
    imbalanced-learn
    numba

[for now]

Thank you

**Comment by oguiza** [comment]
Hi, 
Thanks for raising this issue. 
I've reviewed all imports and have made an update to the repo as well as the pip package. I think I didn't miss anything, but if you have any new issue please let me know.
