### ISSUE TITLE
seq_len for multivariate time series

### ISSUE THREAD

**Issue by vrodriguezf** [timeseriesAI/timeseriesAI#3]
Hi, I am seeing in the first notebook that the attribute `seq_len` when loading the `NATOPS` dataset is marked as 52, but the real length of the sequences if 51 according to the UCR archive.

However, for the ChlorineConcentration dataset it is ok. Is it a problem with multivariate datasets, maybe the feature column is being taken into account as part of `seq_len`?

**Comment by oguiza** [comment]
I've just checked this, and you are right. Good catch!
There was a bug in the code. It was in the databunch creation step from a dataframe. Now it shows 51 as it should.
I've also modified the issue with the cols and feat that you also raised the other day. I've build a check to add cols + feat, so it doesn't matter if you include them or not. Either way it'll work.
