### ISSUE TITLE
Errors in notebook 01 after last commit

### ISSUE THREAD

**Issue by vrodriguezf** [timeseriesAI/timeseriesAI#4]
Hi,

I've noticed two errors in the first notebook after the last commit:
1. In the first databunch, the use of `normalize` should be replaced by `scale`
2. In the function `from_df`, the `feat` argument raises an error unless the feature column is part of the `cols` argument.

Best!

**Comment by oguiza** [comment]
Hi Victor, I've fixed the issue created in this and other nbs. Thanks for raising it!
