### ISSUE TITLE
CUDA cannot allocate memory error

### ISSUE THREAD

**Issue by DrAnoopKulkarni** [timeseriesAI/timeseriesAI#8]
I am trying to use timeserieAI with my own dataset (1D sequences) and learn.fit_one_cycle() gives an error "Can not allocate memory".

Couple of questions?

1) Is the timeserieAI databunch (using TSList) memory heavy? My np array size is only about 150M, but if I load databunch with the suggested approach almost 6-7GB of RAM is taken away.

2) Is there anything I can do?

best regards,
~anoop

**Comment by oguiza** [comment]
Please, try to use the updated timeseriesAI library (based on fastai v2). It should be less memory intensive.
