### ISSUE TITLE
Include FCN and ResCNN in `tsa.models`

### ISSUE THREAD

**Issue by Goschjann** [timeseriesAI/timeseriesAI#9]
Currently, only InceptionTime and ResNet are included in `tsai.models`, in timeseriesAI, also the FCN and ResCNN are integrated (which is great). 

Would be great to have them included as well. 

I would offer to do this myself and create a PR for those two architectures, if this is convenient for you @oguiza 

Great package!

**Comment by oguiza** [comment]
Hi,
Thanks a lot for raising this, and sorry for the late response.
I've just uploaded FCN and ResCNN models to tsai.models. Please, let me know if you have any issues with them.
Take care!

**Comment by Goschjann** [comment]
Nice one! Thank you @oguiza !
